// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Room struct {
	RoomID      string
	RoomName    string
	Description sql.NullString
	RoomOwner   string
}

type User struct {
	ID       string
	Username string
	Password string
}
